services:
  - type: web
    name: foodvision-backend
    runtime: docker
    rootDir: Backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: foodvision-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://foodvision-backend.onrender.com
